animalerie/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.animal_list, name='animal_list'),
    path('animal/<str:id_animal>/', views.animal_detail, name='animal_detail'),
    path('animal/<str:id_animal>/?<str:message>', views.animal_detail, name='animal_detail_mes'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animalerie.urls')),
]

animalerie/models.py
from django.db import models

# Create your models here.
class Equipement(models.Model):
    id_equip = models.CharField(max_length=100, primary_key=True)
    disponibilite = models.CharField(max_length=20)
    photo = models.CharField(max_length=200)
    def __str__(self):
        return self.id_equip
 
 
class Animal(models.Model):
    id_animal = models.CharField(max_length=100, primary_key=True)
    etat = models.CharField(max_length=20)
    type = models.CharField(max_length=20)
    race = models.CharField(max_length=20)
    photo = models.CharField(max_length=200)
    lieu = models.ForeignKey(Equipement, on_delete=models.CASCADE)
    def __str__(self):
        return self.id_animal

animalerie/forms.py
from django import forms
 
from .models import Animal
 
class MoveForm(forms.ModelForm):
 
    class Meta:
        model = Animal
        fields = ('lieu',)

animalerie/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import MoveForm
from .models import Animal, Equipement

# List que contien les animals et equipements sauvargadé!
def animal_list(request):
    animals = Animal.objects.all()
    equipement = Equipement.objects.all()
    return render(request, 'animalerie/animal_list.html', {'animals': animals, 'equipement': equipement})


def verification_animal(id_animal):
    if Animal.objects.filter(pk=id_animal).exists():
        return None
    else:
        print("Désolé " + id_animal+ " n'est pas un équipement connu")
        return None


def change_etat(nouveau_lieu, animal, ancien_lieu):
    authorized_states={'affamé','fatigué','repus','endormi'}
    if animal.etat in authorized_states:
        if nouveau_lieu.id_equip == "mangeoire":
            ancien_lieu.disponibilite = "libre"
            animal.etat = "repus"

        elif nouveau_lieu.id_equip == "roue":
            ancien_lieu.disponibilite = "libre"
            animal.etat = "fatigué"

        elif nouveau_lieu.id_equip == "nid":
            ancien_lieu.disponibilite = "libre"
            animal.etat = "endormi"

        elif nouveau_lieu.id_equip == "litière":
            ancien_lieu.disponibilite = "libre"
            animal.etat = "affamé"
    animal.save()
    ancien_lieu.save()


def change_lieu(nouveau_lieu, ancien_lieu, animal, form):
        error = None
        if nouveau_lieu.id_equip == ancien_lieu.id_equip:
            message = "Félicitations... votre modification a été fait avec success"
            error = True
            return error, nouveau_lieu, ancien_lieu, animal, form, message
        else:
            if (nouveau_lieu.id_equip == "litière"):
                change_etat(nouveau_lieu, animal, ancien_lieu)
                animal.lieu.id_equip = "litière"
                nouveau_lieu.disponibilite = "libre"
                animal.save()
                nouveau_lieu.save()
                form.save() 
                message = "Félicitations... votre modification a été fait avec success"
                error = False
                return error, nouveau_lieu, ancien_lieu, animal, form, message
            else:
                if nouveau_lieu.disponibilite == "occupé":
                    message = "Erreur... essayez à nouveau"
                    error = True
                    return error, nouveau_lieu, ancien_lieu, animal, form, message
                else:
                    change_etat(nouveau_lieu, animal, ancien_lieu)
                    animal.lieu.id_equip = nouveau_lieu.id_equip
                    nouveau_lieu.disponibilite = "occupé"
                    animal.save()
                    nouveau_lieu.save()
                    form.save() 
                    message = "Félicitations... votre modification a été fait avec success"
                    error = False
                    return error, nouveau_lieu, ancien_lieu, animal, form, message


def animal_detail(request, id_animal):
    animal = get_object_or_404(Animal, id_animal=id_animal) #Obtien le nom du animal
    message = ""
    form = MoveForm(request.POST, instance=animal)
    ancien_lieu = get_object_or_404(Equipement, id_equip=animal.lieu.id_equip) #Obtien le lieu avant le changement
    verification_animal(animal)
    if request.method == "POST" and form.is_valid():
        form.save(commit=False)
        nouveau_lieu = get_object_or_404(Equipement, id_equip=animal.lieu.id_equip)  #Obtien le lieu
        error, nouveau_lieu, ancien_lieu, animal, form, message= change_lieu(nouveau_lieu, ancien_lieu, animal, form)
        return render(request,
            'animalerie/animal_detail.html',
            {'animal': animal, 'message': message, 'error': error, 'lieu': ancien_lieu, 'new_lieu':nouveau_lieu, 'form': form})
    else:
        form = MoveForm()
        return render(request,
                  'animalerie/animal_detail.html',
                  {'animal': animal, 'message': message, 'lieu': ancien_lieu, 'form': form})

animalerie/templates/animalerie/animal_detail.html
{% extends 'animalerie/base.html' %}
{% load static %}
{% block content %}

<div class="fakediv">
    <form method="POST" class="post-form">{% csrf_token %}
        <br>
        <h6>Où voulez-vous envoyer votre bébé ?</h6>
        <li><label for="id_lieu"></label> <select name="lieu" required="" id="id_lieu">
            <option value="" selected="">---------</option>
          
            <option value="litière">litière</option>
          
            <option value="mangoire">mangoire</option>
          
            <option value="roue">roue</option>
          
            <option value="nid">nid</option>
          
          </select></li>
    <button class="button button" type="submit">Envoier le au nouvelle lieu!</button>
    <br>
    {% if message == "Erreur... essayez à nouveau" %}
        <div class="alert alert-danger" role="alert">
            {{message}}
        </div>
    {% elif message == "Félicitations... votre modification a été fait avec success" %}
        <div class="alert alert-success" role="alert">
            {{message}}
        </div>
    {% endif %}
    

    <button class="button"><a href="{% url 'animal_list' %}">Ops, je me suis trompé. Je veux retourner a page de selection! </a></button>
    </form>
    <!--<img src="https://i.pinimg.com/474x/eb/cd/a6/ebcda67c2ea4df5c0a3cb7841cd27b61.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Kho ảnh anime | Cute hamsters, Cute animals, Cute animal drawings" data-noaft="1" style="width: 415px; height: 553.333px; margin: 0px;"> -->
    <img src="https://i.pinimg.com/736x/93/12/de/9312de0fb9f582e54cc6ee1cb8fca26a.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Japanese Artist Paints Adorable Watercolours Of Pet Hamster Doing Human  Things | Hamster dibujo, Mascotas memes, Hamsters" data-noaft="1" style="width: 415px; height: 518.75px; margin: 0px;">
    <img src="https://i.pinimg.com/736x/79/a5/93/79a593eb70a2604eeb130fbde803b771.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Pin de NATSUKI (Neko-chan) em ANIME MANGA FANART | Desenhos de animais  fofinhos, Animais bonitos, Hamsters fofos" data-noaft="1" style="width: 415px; height: 518.75px; margin: 0px;">    <img src="https://i.pinimg.com/736x/10/84/9a/10849a5bbec7bcc2ea7d334369cc5c10.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Pin by Isabella Maúlen on hámsters | Cute hamsters, Cute animal drawings,  Cute animals" data-noaft="1" style="width: 415px; height: 518.75px; margin: 0px;">
    <img src="https://i.pinimg.com/originals/64/33/86/6433869ef972b167fb43cf74e0ad40aa.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Pin de Peres en Gotte Hamster Painter | Dibujos bonitos de animales,  Dibujos kawaii de animales, Dibujos bonitos" data-noaft="1" style="width: 415px; height: 408.36px; margin: 0px;">
    <!--<img itemprop="contentUrl" alt="Animales bonitos, dibujos animados, encantador, hámsters png" title="Animales bonitos, dibujos animados, encantador, hámsters png" src="https://w7.pngwing.com/pngs/950/435/png-transparent-cute-animals-cartoon-lovely-hamsters.png" oncontextmenu="return false;"> -->
</div>
 
{% endblock %}

animalerie/templates/animalerie/animal_list.html
{% extends 'animalerie/base.html' %}
{% block content %}

<div class="row">
    <div class="main">
        <h6>Petites créatures en quête d'un foyer </h6>
        <br>
        <hr>
        {% for animal in animals %}
            <div class="main2">
            <h3><button class="button button"><a href="{% url 'animal_detail' id_animal=animal.id_animal %}">{{ animal.id_animal }}<b> : </b></a></button></h3>
            <h5><b>type:</b> <i>{{ animal.type }}</i></h5>
            <h5><b>race:</b> <i>{{ animal.race |linebreaksbr }}</i></h5>
            <h5><b>etat:</b> <i>{{ animal.etat |linebreaksbr }}</i></h5>
            <h5><b>lieu:</b> <i>{{ animal.lieu |linebreaksbr }}</i><h5> 
            </div>
        {% endfor %}
        <hr>
    </div>
    <div class="main">
        <h6>Qu'est-ce qu'elles font maintenant ?</h6>
        <br>
        <hr>
        {% for equip in equipement %}
            <h3 style="background-color: #ee86c1c7;  color: white;border-radius: 18px; padding: 10px 30px; display: block; text-align: center;" >{{ equip.id_equip }}</h3>
            {% if equip.disponibilite == 'libre' %}
                <h4 style="color:green;"><b>  disponibilite: </b><i>{{ equip.disponibilite |linebreaksbr  }}</i></h4>
            {% endif %}
            {% if equip.disponibilite == 'occupé' %}
                <h4 style="color:red;"><b>   disponibilite:   </b><i>{{ equip.disponibilite |linebreaksbr }}</i></h4>

            {% endif %}
        {% endfor %}
        <hr>
    </div>
</div>
{% endblock %}

animalerie/templates/animalerie/base.html
{% load static %}
<html>
    <head>
        <title>Bienvenue à l'animalerie </title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/animalerie.css' %}">
    </head>

    <body>
        <div class="header">
            <h1><img src="https://i.pinimg.com/originals/6d/7f/29/6d7f29434458fc51b4dec7029e951180.jpg" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb KAlRDb" alt="Pin by PN on anime | Cute hamsters, Cute animal drawings, Cute kawaii  animals" data-noaft="1" style="width: 165px; height: 161.25px; margin: 0px;"> Bienvenue à l'animalerie!</h1>
        </div>
            {% block content %}
            {% endblock %}
    </body>

</html>